backend:
  name: git-gateway
  branch: blog

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'frontmatter'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'experience'
    label: 'Experience'
    format: 'frontmatter'
    folder: 'content/experience'
    create: true
    slug: '{{slug}}-{{company}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Start Date', name: 'from_date', widget: 'datetime' }
      - { label: 'Finish Date', name: 'to_date', widget: 'datetime', required: false }
      - { label: 'Keywords', name: 'keywords', widget: 'string' }
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Website', name: 'link', widget: 'string' }
      - { label: 'Taks', name: 'task', widget: 'markdown' }